const wine_keys =
[{ wine: 'Savennieres' },
  { wine: 'German Riesling Spatlese' },
  { wine: 'Chilean Cabernet Sauvignon' },
  { wine: 'California Zinfandel' },
  { wine: 'California Gewurztraminer' },
  { wine: 'Barbaresco' },
  { wine: 'Periquita blend' },
  { wine: 'Alsatian Pinot Blanc' },
  { wine: 'Bourgueil' },
  { wine: 'Bandol' },
  { wine: 'Sauvignon Blanc' },
  { wine: 'California Syrah' },
  { wine: 'Tokay Pinot Gris' },
  { wine: 'Alsatian Gewurztraminer' },
  { wine: 'Australian Shiraz' },
  { wine: 'Rioja-style Tempranillo' },
  { wine: 'Malvasia Bianca' },
  { wine: 'Pinot Blanc' },
  { wine: 'South Africa Chenin Blanc' },
  { wine: 'Negroamaro-Malvasia' },
  { wine: 'Zierfandler' },
  { wine: 'Beaujolais blanc' },
  { wine: 'Priorat' },
  { wine: 'Salice Salentino' },
  { wine: 'Condrieu' },
  { wine: 'California Sauvignon Blanc' },
  { wine: 'Chianti Classico' },
  { wine: 'California Semillon' },
  { wine: 'Chilean Merlot' },
  { wine: 'Muscatel' },
  { wine: 'German Muskateller Kabinett' },
  { wine: 'California Merlot' },
  { wine: 'Australian Cabernet Sauvignon' },
  { wine: 'Chilean Carmenere-Merlot blend' },
  { wine: 'Red Bordeaux' },
  { wine: 'California Pinot Blanc' },
  { wine: 'Getariako Txakolina' },
  { wine: 'Nebbiolo' },
  { wine: 'Red Burgundy' },
  { wine: 'Australian Grenache-Mourvedre-Syrah blend' },
  { wine: 'Minervois' },
  { wine: 'California Cabernet Sauvignon' },
  { wine: 'Aglianico del Vulture' },
  { wine: 'German Gewurztraminer Spatlese' },
  { wine: 'Chardonnay' },
  { wine: 'Cabernet Sauvignon' },
  { wine: 'Sancerre' },
  { wine: 'Italian Pinot Grigio' },
  { wine: 'German Riesling Auslese' },
  { wine: 'California Syrah-Mourvedre-Grenache Blend' },
  { wine: 'Vinho Verde' },
  { wine: 'Albarino' },
  { wine: 'Pinot Noir' },
  { wine: 'Gruner Veltliner' },
  { wine: 'Provencal Mourvedre-Cinsault-Grenache blend' },
  { wine: 'Amarone della Valpolicella' },
  { wine: 'Super Tuscan blend' },
  { wine: 'Syrah' },
  { wine: 'Brunello di Montalcino' },
  { wine: 'Tuscan Sangiovese' },
  { wine: 'White Bordeaux' },
  { wine: 'Sicilian Chardonnay' },
  { wine: 'Pinot Grigio' },
  { wine: 'Dolcetto d\'Alba' },
  { wine: 'Barolo' },
  { wine: 'New Zealand Sauvignon Blanc' },
  { wine: 'Garnacha-Cabernet Sauvignon blend' },
  { wine: 'Barbera d\'Asti' },
  { wine: 'Italian Chardonnay' },
  { wine: 'Carignan' },
  { wine: 'Chardonnay Burgundy' },
  { wine: 'Tempranillo-Garnacha Blend' },
  { wine: 'Alsatian Pinot Gris' },
  { wine: 'Alsatian Riesling' },
  { wine: 'White Burgundy' },
  { wine: 'Barbera d\'Alba' },
  { wine: 'Cornas' },
  { wine: 'Madiran' },
  { wine: 'California Chardonnay' },
  { wine: 'Alsatian Muscat' },
  { wine: 'California Pinot Noir' },
  { wine: 'Spanish Sauvignon Blanc' },
  { wine: 'Chateau Grillet' },
  { wine: 'Pouilly Fume' },
  { wine: 'Oregon Pinot Noir' },
  { wine: 'Cahors' },
  { wine: 'Cotes-du-Rhone' },
  { wine: 'German Riesling Kabinett' },
  { wine: 'Sancerre Rouge' },
  { wine: 'California Viognier' },
  { wine: 'Malbec' },
  { wine: 'Ribera del Duero' },
  { wine: 'Beaujolais cru' },
  { wine: 'Beaujolais' },
  { wine: 'Chilean Sauvignon Blanc' },
  { wine: 'Argentinian Torrontes' },
  { wine: 'Vouvray demi sec' },
  { wine: 'Vouvray sec' }]

module.exports = wine_keys
